version: "3.7"
services:
  web:
    container_name: photos-carosuel-apache-php
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb
    env_file: 
      - .env
